import type { RouteAuthEntry } from './types';

// Group: content. Pre-14.2 there were NO route-level gates and NO service-level allow/deny
// (every authenticated staff role could reach every handler); only ownership/branch/subject
// SCOPE was enforced in services (assertCanModify etc.), which is unchanged.
export const entries: RouteAuthEntry[] = [
  { route: '/api/homework', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.read'] },
  { route: '/api/homework', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.create'] },
  { route: '/api/homework/options', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.read'] },
  { route: '/api/homework/[homeworkId]', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.read'] },
  { route: '/api/homework/[homeworkId]', method: 'PUT', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.update'] },
  { route: '/api/homework/[homeworkId]', method: 'DELETE', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.delete'] },
  { route: '/api/homework/[homeworkId]/submissions', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.read'] },
  { route: '/api/homework/[homeworkId]/submissions/[submissionId]', method: 'PATCH', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.update'] },
  { route: '/api/materials', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.read'] },
  { route: '/api/materials', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.create'] },
  { route: '/api/materials/[materialId]', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.read'] },
  { route: '/api/materials/[materialId]', method: 'PUT', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.update'] },
  { route: '/api/materials/[materialId]', method: 'DELETE', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.delete'] },
  { route: '/api/questions', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.read'] },
  { route: '/api/questions', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.create'] },
  { route: '/api/questions/options', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.read'], note: 'authoring options; read permission' },
  { route: '/api/questions/[questionId]', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.read'] },
  { route: '/api/questions/[questionId]', method: 'PUT', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.update'] },
  { route: '/api/questions/[questionId]', method: 'DELETE', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.delete'] },
  { route: '/api/questions/[questionId]/duplicate', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.create'] },
  { route: '/api/question-papers', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['question_papers.read'] },
  { route: '/api/question-papers', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['question_papers.create'] },
  { route: '/api/question-papers/[paperId]', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['question_papers.read'] },
  { route: '/api/question-papers/[paperId]', method: 'PUT', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['question_papers.update'] },
  { route: '/api/question-papers/[paperId]/archive', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['question_papers.update'] },
  { route: '/api/question-papers/[paperId]/finalize', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['question_papers.finalize'] },
  { route: '/api/notices', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.read'] },
  { route: '/api/notices', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.create'] },
  { route: '/api/notices/[noticeId]', method: 'GET', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.read'] },
  { route: '/api/notices/[noticeId]', method: 'PUT', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.update'], note: 'service keeps: editing a PUBLISHED notice needs OWNER/ADMIN (business-state rule, not a gate); teacher audience + ownership scope kept' },
  { route: '/api/upload', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['upload.use'] },
  { route: '/api/homework/[homeworkId]/archive', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.publish'] },
  { route: '/api/homework/[homeworkId]/close', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.publish'] },
  { route: '/api/homework/[homeworkId]/publish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.publish'] },
  { route: '/api/homework/[homeworkId]/restore', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.publish'] },
  { route: '/api/homework/[homeworkId]/unpublish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['homework.publish'] },
  { route: '/api/materials/[materialId]/archive', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.publish'] },
  { route: '/api/questions/[questionId]/archive', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.publish'] },
  { route: '/api/notices/[noticeId]/archive', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.publish'] },
  { route: '/api/materials/[materialId]/publish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.publish'] },
  { route: '/api/questions/[questionId]/publish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.publish'] },
  { route: '/api/notices/[noticeId]/publish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.publish'] },
  { route: '/api/materials/[materialId]/restore', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.publish'] },
  { route: '/api/questions/[questionId]/restore', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.publish'] },
  { route: '/api/notices/[noticeId]/restore', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.publish'] },
  { route: '/api/materials/[materialId]/unpublish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['materials.publish'] },
  { route: '/api/questions/[questionId]/unpublish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['questions.publish'] },
  { route: '/api/notices/[noticeId]/unpublish', method: 'POST', oldRoles: ['OWNER', 'ADMIN', 'STAFF', 'TEACHER'], permissions: ['notices.publish'] },
  { route: '/api/notifications', method: 'GET', oldRoles: 'ANY', permissions: null, note: 'per-user notifications (scoped to the caller userId); intentionally ungated' },
  { route: '/api/notifications/read-all', method: 'POST', oldRoles: 'ANY', permissions: null, note: 'per-user notifications (scoped to the caller userId); intentionally ungated' },
  { route: '/api/notifications/unread-count', method: 'GET', oldRoles: 'ANY', permissions: null, note: 'per-user notifications (scoped to the caller userId); intentionally ungated' },
  { route: '/api/notifications/[notificationId]/read', method: 'POST', oldRoles: 'ANY', permissions: null, note: 'per-user notifications (scoped to the caller userId); intentionally ungated' },
];
